export enum LocalStorageKey {
    HiddenBranches = 'HiddenBranches',
    BranchHistory = 'BranchHistory',
    CommitMessage = 'CommitMessage',
    PrecommitCommand = 'PrecommitCommand',
    StatusCalledAt = 'StatusCalledAt',
    FetchCalledAt = 'FetchCalledAt',
    CurrentRepositoryPath = 'CurrentRepositoryPath',
    RepositoryPaths = 'RepositoryPaths',
    CreatePullRequestUrlTemplate = 'CreatePullRequestUrlTemplate',
    UseBranchAsCommitMessagePrefix = 'UseBranchAsCommitMessagePrefix',
    UseSectionCommitMessagePrefix = 'UseSectionCommitMessagePrefix',
    PushOnCommit = 'PushOnCommit',
    SectionCommitMessagePrefix = 'SectionCommitMessagePrefix',
    JiraPath = 'JiraPath',
    JiraUser = 'JiraUser',
    JiraToken = 'JiraToken',
    JiraIssueSummaries = 'JiraIssueSummaries',

    YoutrackPath = 'YoutrackPath',
    YoutrackToken = 'YoutrackToken',
    YoutrackIssueSummaries = 'YoutrackIssueSummaries',

    StageAllFilesBeforeCommit = 'StageAllFilesBeforeCommit',
    CleanAfterCommit = 'CleanAfterCommit',
}
