export enum LocalStorageKey {
    HiddenBranches = 'HiddenBranches',
    BranchHistory = 'BranchHistory',
    CommitMessage = 'CommitMessage',
    PrecommitCommand = 'PrecommitCommand',
    StatusCalledAt = 'StatusCalledAt',
    FetchCalledAt = 'FetchCalledAt',
    CurrentRepositoryPath = 'CurrentRepositoryPath',
    RepositoryPaths = 'RepositoryPaths',
    CreatePullRequestUrlTemplate = 'CreatePullRequestUrlTemplate',
    GitlabRepositoryPath = 'GitlabRepositoryPath',
    UseBranchAsCommitMessagePrefix = 'UseBranchAsCommitMessagePrefix',
    UseSectionCommitMessagePrefix = 'UseSectionCommitMessagePrefix',
    SectionCommitMessagePrefix = 'SectionCommitMessagePrefix',
    JiraPath = 'JiraPath',
    JiraUser = 'JiraUser',
    JiraToken = 'JiraToken',
    JiraIssueSummaries = 'JiraIssueSummaries',
    StageAllFilesBeforeCommit = 'StageAllFilesBeforeCommit',
    CleanAfterCommit = 'CleanAfterCommit',
}
