export enum LocalStorageKey {
    HiddenBranches = 'HiddenBranches',
    BranchHistory = 'BranchHistory',
    CommitMessage = 'CommitMessage',
    PrecommitCommand = 'PrecommitCommand',
    StatusCalledAt = 'StatusCalledAt',
    FetchCalledAt = 'FetchCalledAt',
    CurrentRepositoryPath = 'CurrentRepositoryPath',
    RepositoryPaths = 'RepositoryPaths',
    BitbucketRepositoryPath = 'BitbucketRepositoryPath',
    UseBranchAsCommitMessagePrefix = 'UseBranchAsCommitMessagePrefix',
    UseSectionCommitMessagePrefix = 'UseSectionCommitMessagePrefix',
    SectionCommitMessagePrefix = 'SectionCommitMessagePrefix',
    JiraPath = 'JiraPath',
    JiraUser = 'JiraUser',
    JiraToken = 'JiraToken',
    JiraIssueSummaries = 'JiraIssueSummaries',
    CleanAfterCommit = 'CleanAfterCommit',
}
